// Generated by CoffeeScript 1.7.1
var concat, gulp, jsFiles, jshint, rename, sass, uglify;

gulp = require('gulp');

jshint = require('gulp-jshint');

sass = require('gulp-sass');

concat = require('gulp-concat');

uglify = require('gulp-uglify');

rename = require('gulp-rename');

jsFiles = ['src/*.js', 'src/services/*.js', 'src/controllers/*.js', 'src/directives/*.js'];

gulp.task('lint', function() {
  return gulp.src(jsFiles).pipe(jshint()).pipe(jshint.reporter('default'));
});


/*
 * Compile Our Sass
gulp.task 'sass', ->
  gulp.src('scss/*.scss')
    .pipe(sass())
    .pipe gulp.dest('css')
 */

gulp.task('scripts', function() {
  return gulp.src(jsFiles).pipe(concat('rogue-like-like.js')).pipe(gulp.dest('dist')).pipe(rename('rogue-like-like.min.js')).pipe(uglify()).pipe(gulp.dest('dist'));
});

gulp.task('watch', function() {
  gulp.watch(jsFiles, ['lint', 'scripts']);
});

gulp.task('default', ['lint', 'scripts', 'watch']);
