// Generated by CoffeeScript 1.7.1
(function(ng, app) {
  'use strict';
  return app.controller('MainController', function($scope, boardConfig) {
    $scope.board = boardConfig;
  });
})(angular, rogueLikeLike);
