// Generated by CoffeeScript 1.7.1
Game.io = {
  messages: [],
  ws: new WebSocket('ws://localhost:8080/')
};

Game.io.ws.onopen = (function(_this) {
  return function(evt) {
    console.log("closed socket", evt);
    Game.start();
    return evt;
  };
})(this);

Game.io.ws.onclose = (function(_this) {
  return function(evt) {
    console.log("closed socket", evt);
    return evt;
  };
})(this);

Game.io.ws.onmessage = (function(_this) {
  return function(evt) {
    console.log("message on socket", evt);
    return evt;
  };
})(this);

Game.io.ws.onerror = function(evt) {
  console.log('WEBSOCKET ERROR', evt);
  return evt;
};
